### ISSUE TITLE
Controller movement

### ISSUE THREAD

**Issue by davidalpha** [GuBaDa/NewGame#1]
- Strafe
- 2 stick control
- action buttons

**Comment by Maxic** [comment]
Abuse-style top down shooter controls implemented. Left stick indicates direction and movement, untill right stick is used. Then, right stick is used for direction and left for movement only (Strafing). Strafing slows down the player. 

Current action buttons: 
- Fire (Right trigger)
- Run (Right bumper)

Used external asset for easy Xbox controller mapping. 

Implemented with commit: d1c21d6
